name: Cryptic Backend Docker Image
on:
  push:
    branches: [experimental]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew installDist
      - name: Grant execute permission for docker-entrypoint.sh
        run: chmod +x docker/docker-entrypoint.sh
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: rubidiumdev/cryptic-backend
          tags: latest
